#!/usr/bin/python3
# -*- coding: utf-8 -*-

from tkinter import *

#Scores#
score=0
score2=0
#Coordonnées#
PosX=60
PosY=10
PosX2=480
PosY2=200
PosW2=10
PosZ2=480
#Vitesse balle#
dx=2
dy=2
   
##########Bouton quitter##########
def fin ():
    canvas.quit()
    canvas.destroy()
    
#########Bouton jouer#########
def jouer():
    global canvas
 
#########Déplacements de la balle et collision avec raquettes############"
    def deplacement():
        global dx, dy, PosX2, PosY2, score, score2
        if canvas.coords(balle)[1]<0:
            dy=-1*dy
        if canvas.coords(balle)[2]>=PosY2 and canvas.coords(balle)[2]>=canvas.coords(raquette1)[0] and canvas.coords(balle)[0]<=canvas.coords(raquette1)[2] and canvas.coords(balle)[3]<=490:
            dx=-1*dx
            score=score+1
            TextGame.set("Score joueur 1: "+ str(score))
        if canvas.coords(balle)[0]<=PosY2 and canvas.coords(balle)[2]>=canvas.coords(raquette2)[0] and canvas.coords(balle)[0]<=canvas.coords(raquette2)[2] and canvas.coords(balle)[3]<=210:
            dx=-1*dx
            score2=score2+1
            TextGame2.set("Score joueur 2: "+ str(score2))
        if canvas.coords(balle)[3]>500:
            dy=-1*dy
        if canvas.coords(balle)[3]<540:
            tk.after(10,deplacement)
        canvas.move(balle,dx,dy)
        	
        
######Touches du clavier pour déplacer les raquettes###########
    def KeyBoard(event):
        global PosY2, canvas
        Key = event.keysym
 
        if Key == 'm':
            canvas.move(raquette1,0,30)
        if Key == 'p':
            canvas.move(raquette1,0,-30)
        if Key == 's':
            canvas.move(raquette2,0,30)
        if Key == 'z':
            canvas.move(raquette2,0,-30)
 
###### Nouveau canevas et destruction du lanceur######
    canvas.destroy()
    tk = Tk()
    tk.title("[Pong]")
 
    canvas = Canvas(tk,width = 500, height = 500 , bd=0, bg="grey")
    canvas.pack(padx=10,pady=10)
    #canvas.create_line(PosX2+100,PosY2+10,PosX2,PosY2,fill="white",dash=(5,10),width=5)#

    
 ######## Balle et raquette ##################
    balle = canvas.create_oval(PosX,PosY,PosX+20,PosY+20,fill='orange')
    raquette1 = canvas.create_rectangle(PosX2+10,PosY2+100,PosX2,PosY2,fill='black')
    raquette2 = canvas.create_rectangle(PosW2+10,PosW2,PosW2,PosW2+100,fill='black')
    
 ###########Scoreboard###################
    TextGame = StringVar()
    LabelGame = Label(tk, textvariable = TextGame , bg ="grey")
    TextGame.set("Score joueur 1: "+ str(score))
    LabelGame.pack(padx = 1, pady = 5)
    
    TextGame2 = StringVar()
    LabelGame2 = Label(tk, textvariable = TextGame2 , bg ="grey")
    TextGame2.set("Score joueur 2: "+ str(score2))
    LabelGame2.pack(padx = 20, pady = 5)
 
 ################ Refraichissement en boucle ##################
    canvas.focus_set()
    canvas.bind('<Key>',KeyBoard)
    deplacement()
    tk.mainloop()
    
##########Bouton credits###########
def credits ():
	global canvas
	
	canvas.destroy()
	crd = Tk()
	crd.title("[Crédits]")
	TextCredit=Label(crd,text="Jeu Pong par\n Pierre Bouffartigue\n Année 2018 - 2019\n", fg="orange",bg="black").pack()
	BoutonRetour=Button(crd,text="Retour au menu", command=rtm).pack()
	
############## Menu options ##############
def options ():
	global canvas
	
	canvas.destroy()
	opt = Tk()
	opt.title("[Options]")
	BoutonRetour=Button(inst,text="Retour au menu", command=rtm).pack()

#########Bouton instructions########"
def instructions ():
	global canvas
	
	canvas.destroy()
	inst = Tk()
	inst['bg'] = 'black'
	inst.title("[Instructions]")
	TextCredit=Label(inst,text="-[PONG]-", fg="red",bg="black").pack()
	TextCredit=Label(inst,text="Ce jeu reprend le principe du tennis de table.\n A deux joueurs vous devrez vous renvoyer \nla balle et marquer un maximum de points.\n Si un joueur ne renvoie pas la balle\n et qu'elle touche le bord derrière sa raquette,\n un point sera marqué.\n", fg="orange",bg="black").pack()
	TextCredit=Label(inst,text="Joueur 1 (gauche), utilise les touches Z et S\n Joueur 2 (droite), utilise les touches P et M\n", fg="green",bg="black").pack()
	BoutonRetour=Button(inst,text="Retour au menu", command=rtm).pack()

###########Canvas principal (menu) #################
canvas = Tk()
canvas.geometry("170x230")
canvas.title("-Pong-")
    
###########Boutons et texte du menu de lancement#################

TextIndication=Label(canvas,text="Avant de débuter une\n partie assurez vous\n  d'avoir pris connaissance\n  des instructions \n disponibles ci-dessous.", fg="black").pack()

BoutonInstructions=Button(canvas,text="Instructions", command=instructions).pack()
BoutonJouer = Button(canvas, text ="   Jouer   ", command = jouer, bg ="blue", fg="white").pack()
BoutonOptions=Button(canvas,text="Options", command=fin).pack()
BoutonCredits=Button(canvas,text="Credits", command=credits).pack()
BoutonQuit=Button(canvas,text="Quitter", command=fin, fg="red").pack()
TextPlus=Label(canvas,text="Jeu Pong - 2019").pack()

##########Bouton "retour" au menu#####
def rtm ():  
	canvas = Tk()
	canvas.geometry("170x230")
	canvas.title("-Pong-")
	TextIndication=Label(canvas,text="Avant de débuter une\n partie assurez vous\n  d'avoir pris connaissance\n  des instructions \n disponibles ci-dessous.", fg="black").pack()

	BoutonInstructions=Button(canvas,text="Instructions", command=instructions).pack()
	BoutonJouer = Button(canvas, text ="   Jouer   ", command = jouer, bg ="blue", fg="white").pack()
	BoutonOptions=Button(canvas,text="Options", command=options).pack()
	BoutonCredits=Button(canvas,text="Credits", command=credits).pack()
	BoutonQuit=Button(canvas,text="Quitter", command=fin, fg="red").pack()
	TextPlus=Label(canvas,text="Jeu Pong - 2019").pack()

#########Boucle infinie pour que le jeu ne se termine qu'en fin de partie########

canvas.mainloop()
